export const metadata = {
  title: 'Disclaimer — Cricket by the Books',
}

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen gradient-hero">
      <header className="sticky top-0 z-50 glass border-b border-gray-100/50">
        <div className="max-w-3xl mx-auto px-6 py-4 flex items-center gap-3">
          <a href="/" className="text-gray-400 hover:text-emerald-600 transition-colors p-1 rounded-lg hover:bg-emerald-50">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
          </a>
          <span className="font-semibold text-gray-900 text-sm tracking-tight">Cricket by the Books</span>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-16 animate-fade-in">
        <h1 className="text-2xl font-bold text-gray-900 mb-2">Disclaimer</h1>
        <p className="text-xs text-gray-400 mb-10">Effective April 2026</p>

        <div className="space-y-8 text-sm text-gray-600 leading-relaxed">
          <section>
            <h2 className="text-base font-semibold text-gray-800 mb-2">Independent Tool</h2>
            <p>
              Cricket by the Books is an independent, community-run project and is not affiliated with,
              endorsed by, or officially connected to Cricket Quebec, Cricket BC, Cricket Canada, or any
              other cricket governing body.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-800 mb-2">AI-Generated Answers</h2>
            <p>
              All answers are generated by an AI system based solely on official documents that have been
              uploaded to this platform. While every effort is made to provide accurate, document-grounded
              responses, answers may not reflect the most current version of a policy, may be incomplete,
              or may be misinterpreted by the AI. Always verify important information directly with your
              cricket organization.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-800 mb-2">Not Legal Advice</h2>
            <p>
              Nothing on this platform constitutes legal advice. For formal matters — including
              disciplinary proceedings, eligibility disputes, appeals, or registration issues — consult
              directly with your cricket organization or a qualified legal professional.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-800 mb-2">No Warranty</h2>
            <p>
              This tool is provided as-is, in alpha, with no guarantees of accuracy, availability, or
              completeness. Use of this tool is at your own discretion.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-800 mb-2">Document Currency</h2>
            <p>
              Cricket policies change. The documents indexed on this platform reflect versions available
              at the time of upload. If you believe a policy has been updated, please{' '}
              <a href="/contact" className="text-emerald-600 hover:text-emerald-700 underline underline-offset-2">
                let us know
              </a>
              .
            </p>
          </section>
        </div>
      </main>
    </div>
  )
}
